version: '2.2'

services:
    mariadb:
      restart: always
      image: mariadb:10.6
      expose:
        - "3306"
      environment:
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      healthcheck:
        test: [ "CMD", "/usr/local/bin/healthcheck.sh", "--su=root", "--connect", "--innodb_initialized" ]
        retries: 5
      volumes:
        - mariadb-data:/var/lib/mysql

    redis:
      restart: always
      image: redis:latest
      expose:
        - "6379"
      healthcheck:
        test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
        retries: 5
      volumes:
        - redis-data:/data

    elasticsearch:
      restart: always
      image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.6
      command: elasticsearch -Enetwork.bind_host=0.0.0.0 -Ehttp.max_content_length=2000mb
      ports:
        - 9200:9200
      environment:
        - ES_JAVA_OPTS=-Xms2g -Xmx2g
        - ANONYMOUS_USER=true
      volumes:
        - elastic-data:/usr/share/elasticsearch/data

    kibiter:
      restart: always
      image: bitergia/kibiter:community-v6.8.6-3
      environment:
        - PROJECT_NAME=Demo
        - NODE_OPTIONS=--max-old-space-size=1000
        - ELASTICSEARCH_URL=http://elasticsearch:9200
      links:
        - elasticsearch
      ports:
        - 5601:5601

    mordred:
      restart: always
      image: wiremock/grimoirelab:latest
      build:
        context: .
        dockerfile: grimoirelab.Dockerfile
      volumes:
        - ./settings/setup.cfg.template:/sirmordred-setup.cfg.template
        - ./settings/projects.json:/home/grimoire/conf/projects.json
        - /tmp/:/home/grimoire/logs
      depends_on:
        nginx:
          condition: service_healthy
      mem_limit: 4g
      secrets:
        - github-api-token

    sortinghat:
      restart: always
      image: grimoirelab/sortinghat:0.17.0
      environment:
        - SORTINGHAT_SECRET_KEY=secret
        - SORTINGHAT_DB_HOST=mariadb
        - SORTINGHAT_DB_PORT=3306
        - SORTINGHAT_DB_DATABASE=sortinghat_db
        - SORTINGHAT_DB_USER=root
        - SORTINGHAT_DB_PASSWORD=
        - SORTINGHAT_REDIS_HOST=redis
        - SORTINGHAT_REDIS_PASSWORD=
        - SORTINGHAT_SUPERUSER_USERNAME=root
        - SORTINGHAT_SUPERUSER_PASSWORD=root
        - SORTINGHAT_ALLOWED_HOST=sortinghat,nginx,localhost,127.0.0.1,[::1]
        - SORTINGHAT_CORS_ALLOWED_ORIGINS=http://localhost:8000,http://127.0.0.1:8000
      expose:
        - "9314"
      volumes:
        - sortinghat-static:/opt/venv/lib/python3.9/site-packages/sortinghat/static/
        - ./settings/orgs_file.json:/home/grimoirelab/settings/orgs_file.json
      depends_on:
        mariadb:
          condition: service_healthy
        redis:
          condition: service_healthy

    sortinghat_worker:
      restart: always
      image: grimoirelab/sortinghat-worker:0.17.0
      environment:
        - SORTINGHAT_SECRET_KEY=secret
        - SORTINGHAT_DB_HOST=mariadb
        - SORTINGHAT_DB_PORT=3306
        - SORTINGHAT_DB_DATABASE=sortinghat_db
        - SORTINGHAT_DB_USER=root
        - SORTINGHAT_DB_PASSWORD=
        - SORTINGHAT_REDIS_HOST=redis
        - SORTINGHAT_REDIS_PASSWORD=
      depends_on:
        mariadb:
          condition: service_healthy
        redis:
          condition: service_healthy
      volumes:
        - ./settings/orgs_file.json:/home/grimoirelab/settings/orgs_file.json

    nginx:
      restart: always
      image: nginx:latest
      volumes:
        - ./settings/nginx.conf.template:/etc/nginx/templates/default.conf.template
        - ./settings/uwsgi_params:/etc/nginx/uwsgi_params
        - sortinghat-static:/sortinghat:ro
      ports:
        - 8000:8000
      environment:
        - KIBANA_HOST=http://kibiter:5601/
      depends_on:
        - sortinghat
      healthcheck:
        test: "curl -s --head http://localhost:8000/identities/api/ | grep Set-Cookie || exit 1"
        retries: 5

volumes:
  sortinghat-static:
  mariadb-data:
  redis-data:
  elastic-data:

secrets:
  github-api-token:
    file: ./settings/github-api-token.txt
